# Generated by Django 3.1.7 on 2021-02-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(max_length=500)),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
